spring:
  application:
    name: api-gateway

  config:
    import:
      - "optional:configserver:http://localhost:8888"
  cloud:
    config:
      username: configuration
      password: config@123
  profiles:
    active:
    - dev